services:
  - type: web
    name: android-device-manager
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --legacy-peer-deps && cd client && npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://repodeploy.vercel.app
